<?php /* Smarty version 2.6.20, created on 2010-03-24 16:41:07
         compiled from header.tpl */

$this->_cache_serials['/var/www/joomla2/cache/com_agora/en-GB^%%F7^F7F^F7F34188%%header.tpl.inc'] = 'd667efef7741db93b82e19b21fdaf543';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'style', 'header.tpl', 1, false),array('function', 'script', 'header.tpl', 8, false),array('function', 'loadModule', 'header.tpl', 27, false),array('function', 'url', 'header.tpl', 36, false),array('modifier', 'truncate', 'header.tpl', 41, false),)), $this); ?>
<?php
function _smarty_tplfunc_d667efef7741db93b82e19b21fdaf543_0(&$_smarty)
{
echo $_smarty->_plugins['function']['script'][0][0]->agoraScript(array('src' => "js/dropdown_index.js"), $_smarty);
}


function _smarty_tplfunc_d667efef7741db93b82e19b21fdaf543_1(&$_smarty)
{
echo $_smarty->_plugins['function']['script'][0][0]->agoraScript(array('src' => "js/dropdown.js"), $_smarty);
}


function _smarty_tplfunc_d667efef7741db93b82e19b21fdaf543_2(&$_smarty)
{
echo $_smarty->_plugins['function']['script'][0][0]->agoraScript(array('src' => "js/slimbox.js"), $_smarty);
}


function _smarty_tplfunc_d667efef7741db93b82e19b21fdaf543_3(&$_smarty)
{
echo $_smarty->_plugins['function']['script'][0][0]->agoraScript(array('src' => "js/jquery-1.3.2.min.js"), $_smarty);
}



?>
